name: "Bazil"
description: "Filesystem hacking in Go"
nav:
  - doc: documentation
  - fuse:
  - talks:

toc:
  doc:
    - .: Introduction
    - status: Status
    - install: Installation
    - usage: Usage
    - architecture: Architecture
    - antigoals: Anti-goals
    - roadmap: Roadmap
    - related: Related work
