#!/bin/sh
set -e

. "$(git --exec-path)/git-sh-setup"
cd_to_toplevel

export GIT_INDEX_FILE="$GIT_DIR/index.github-pages"
rm -f -- "$GIT_INDEX_FILE"

# hugo does not clean up old clutter
rm -rf public

hugo 1>&2

find content/talks/ -mindepth 2 -maxdepth 2 -name '*.slide' -type f -printf '%h\n' \
    | uniq \
    | while read p; do
    rm -rf temp/represent
    mkdir -p temp/represent
    cp -r "$p"/* temp/represent
    rm -f temp/represent/*.html temp/represent/*.md
    represent -src="temp/represent" -publish="$p"
    rm -rf temp/represent
done

if git diff-index --quiet HEAD; then
    echo "$(basename "$0"): dirty, not publishing" 1>&2
    exit 0
fi

if [ "$(git symbolic-ref HEAD)" != "refs/heads/master" ]; then
    echo "$(basename "$0"): not on master, not publishing" 1>&2
    exit 0
fi

find public/ -type f -print0 \
| git update-index --add --replace -z --stdin

TREE="$(git write-tree --prefix=public/)"

COMMIT="$(git commit-tree "$TREE" <<EOF
Regenerated site.
EOF
)"
echo git push https://github.com/bazil/bazil.github.io +"$COMMIT":refs/heads/master 1>&2
echo $COMMIT
