#!/bin/sh
set -e

. "$(git --exec-path)/git-sh-setup"
cd_to_toplevel

export GIT_INDEX_FILE="$GIT_DIR/index.github-pages"

rm -f -- "$GIT_INDEX_FILE"

jkl .

rm -rf _site/fuse/talks/2013-06-10-la-gophers/
represent -src=fuse/talks/2013-06-10-la-gophers/ -publish=_site/fuse/talks/2013-06-10-la-gophers/

# jkl puts this script in _site also, doesn't support any kind of
# exclude mechanism right now.
rm -f _site/update

# static content, please don't run jekyll
touch _site/.nojekyll

find _site/ -type f -print0 \
| git update-index --add --replace -z --stdin

TREE="$(git write-tree --prefix=_site/)"

COMMIT="$(git commit-tree "$TREE" <<EOF
Regenerated site.
EOF
)"
git push https://github.com/bazillion/bazillion.github.com +"$COMMIT":refs/heads/master
