#!/bin/sh
set -e

. "$(git --exec-path)/git-sh-setup"
cd_to_toplevel

export GIT_INDEX_FILE="$GIT_DIR/index.github-pages"

rm -f -- "$GIT_INDEX_FILE"

jkl .

find talks/ -mindepth 1 -maxdepth 1 -type d \
| while read p; do
    rm -rf -- _site/"$p"
    represent -src="$p" -publish=_site/"$p"
done

# jkl puts this script in _site also, doesn't support any kind of
# exclude mechanism right now.
rm -f _site/update

# static content, please don't run jekyll
touch _site/.nojekyll

if git diff-index --quiet HEAD; then
    echo "$(basename "$0"): dirty, not publishing" 1>&2
    exit 0
fi

if [ "$(git symbolic-ref HEAD)" != "refs/heads/master" ]; then
    echo "$(basename "$0"): not on master, not publishing" 1>&2
    exit 0
fi

find _site/ -type f -print0 \
| git update-index --add --replace -z --stdin

TREE="$(git write-tree --prefix=_site/)"

COMMIT="$(git commit-tree "$TREE" <<EOF
Regenerated site.
EOF
)"
git push https://github.com/bazillion/bazillion.github.io +"$COMMIT":refs/heads/master
